#GENERALES
spring.config.import=optional:file:.env[.properties]
spring.application.name=CitaMed
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/CitaMed}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.jpa.hibernate.ddl-auto=update
spring.output.ansi.enabled=ALWAYS
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

#HIKARICP CONNECTION POOL
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000

#FILE UPLOAD
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

# Directorio base para subida de archivos
app.upload.dir=uploads

#JWT
jwt.secret=miClaveSecretaSuperSeguraDeAlMenos32Caracteres123
jwt.expiration=28800000

#THYMELEAF
spring.thymeleaf.cache=false

#API RENIEC
reniec.api.url=${RENIEC_API_URL}
reniec.api.token=${RENIEC_API_TOKEN}

#STRIPE
stripe.secret-key=${STRIPE_SECRET_KEY}

#PDF SERVICE
pdf.service.url=${PDF_SERVICE_URL:http://localhost:3005}

#API EMAIL (GMAIL SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_EMAIL}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
