#GENERALES
spring.application.name=CitaMed
spring.datasource.url=jdbc:mysql://localhost:3306/CitaMed
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.output.ansi.enabled=ALWAYS
spring.jpa.show-sql=true

#JWT
jwt.secret=miClaveSecretaSuperSeguraDeAlMenos32Caracteres123
jwt.expiration=28800000

#API RENIEC
reniec.api.url=https://api.decolecta.com/v1/reniec/dni
reniec.api.token=sk_15045.yhkSJUcoyl5iOPjXQ1m2C2F9UNNPiwlx

#API EMAIL
mailersend.api.token=mlsn.407650696fa991c5a32bc21787884162276d9fc67929ad62bccf7d107b72496e
mailersend.from.email=info@test-vz9dlemy1p74kj50.mlsender.net
mailersend.from.name=CitaMed